import {useEffect,useState} from 'react';
import {Home,CalendarDays,CheckSquare,Search,Settings as SettingsIcon,Mic,Square,ChevronRight,ChevronDown,X,Pencil,Plus,Trash2,Download} from 'lucide-react';
import {api,apiFile} from './api';
type Page='home'|'meetings'|'tasks'|'search'|'settings'|'detail'; type Any=Record<string,any>;
const fmt=(iso?:string)=>iso?new Intl.DateTimeFormat(undefined,{dateStyle:'long',timeStyle:'short'}).format(new Date(iso)):'';
function App(){const [page,setPage]=useState<Page>('home'),[status,setStatus]=useState<Any>({state:'idle'}),[meetings,setMeetings]=useState<Any[]>([]),[tasks,setTasks]=useState<Any[]>([]),[selected,setSelected]=useState<Any>(),[error,setError]=useState(''),[query,setQuery]=useState('');
 const refresh=()=>{api<Any>('/status').then(setStatus);api<Any[]>('/meetings').then(setMeetings);api<Any[]>('/tasks/me').then(setTasks)};
 useEffect(()=>{refresh();const t=setInterval(refresh,2500);return()=>clearInterval(t)},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.metaKey&&e.key==='k'){e.preventDefault();setPage('search')}};addEventListener('keydown',key);return()=>removeEventListener('keydown',key)},[]);
 const open=async(id:string)=>{setSelected(await api('/meetings/'+id));setPage('detail')};
 const start=async()=>{try{setError('');await api('/recording/start',{method:'POST',body:JSON.stringify({title:status.detected_title||'Untitled meeting',meet_url:status.detected_url})});refresh()}catch(e:any){setError(e.message)}};
 const stop=async()=>{try{await api('/recording/stop',{method:'POST'});refresh()}catch(e:any){setError(e.message)}};
 const remove=async(id:string)=>{await api('/meetings/'+id,{method:'DELETE'});if(selected?.id===id){setSelected(undefined);setPage('meetings')}refresh()};
 const retry=async(id:string,retranscribe=false)=>{setError('');await api('/meetings/'+id+'/retry',{method:'POST',body:JSON.stringify({retranscribe})});refresh()};
 const toggle=async(t:Any)=>{await api('/tasks/'+t.id,{method:'PATCH',body:JSON.stringify({status:t.status==='open'?'completed':'open'})});refresh();if(selected)open(selected.id)};
 const proc=status.processing||{state:'idle',progress:0,queued:[]},busy=['recorded','transcribing','analyzing'].includes(proc.state);
 const nav=[['home',Home,'Home'],['meetings',CalendarDays,'Meetings'],['tasks',CheckSquare,'My Tasks'],['search',Search,'Search']];
 return <div className="shell"><aside><div className="brand"><span>MA</span>Meeting AI</div><nav>{nav.map(([p,I,l]:any)=><button className={page===p?'active':''} onClick={()=>setPage(p)}><I size={17}/>{l}</button>)}</nav><button className="settings" onClick={()=>setPage('settings')}><SettingsIcon size={17}/>Settings</button></aside><main>
  <header><div className={'status '+(status.recording?'recording':proc.state==='failed'||status.state==='failed'?'failed':busy?'transcribing':status.state)}><i/>{status.recording?busy?`Recording · processing previous ${proc.progress}%`:'Recording':busy?`Processing · ${proc.progress}%`:proc.state==='failed'||status.state==='failed'?'Needs attention':status.state==='waiting_for_confirmation'?'Meet detected':'Ready'}</div>{status.recording?<button className="stop" onClick={stop}><Square size={14}/>Stop recording</button>:<button className="primary" onClick={start}><Mic size={15}/>Start recording</button>}</header>
  {error&&<div className="error"><span>{error}</span><X size={16} onClick={()=>setError('')}/></div>}
  {page==='home'&&<HomePage meetings={meetings} tasks={tasks} open={open} toggle={toggle} status={status}/>} {page==='meetings'&&<MeetingList meetings={meetings} open={open} remove={remove}/>} {page==='tasks'&&<Tasks tasks={tasks} toggle={toggle}/>} {page==='search'&&<SearchPage query={query} setQuery={setQuery} open={open}/>} {page==='settings'&&<Settings/>} {page==='detail'&&selected&&<Detail m={selected} toggle={toggle} retry={retry} remove={remove} onSaved={(updated:Any)=>{setSelected(updated);refresh()}}/>}</main></div>}
function HomePage({meetings,tasks,open,toggle,status}:Any){return <section><p className="eyebrow">OVERVIEW</p><h1>Good evening, Hussain</h1><p className="lede">Your meetings at a glance.</p>{status.state==='waiting_for_confirmation'&&<div className="detect"><b>Google Meet detected</b><span>{status.detected_title}</span><p>Recording only begins after you press Start recording.</p></div>}{status.state==='failed'&&status.error&&<div className="processing failed"><div className="processing-head"><div><b>Recording stopped</b><span>{status.stage_detail}</span></div></div><p>{status.error}</p></div>}{['recorded','transcribing','analyzing','failed'].includes(status.processing?.state)&&<Processing status={status.processing}/>}<Block title="MY OPEN TASKS">{tasks.filter((x:Any)=>x.status==='open').slice(0,5).map((t:Any)=><Task t={t} toggle={toggle}/>)}</Block><Block title="RECENT MEETINGS">{meetings.slice(0,6).map((m:Any)=><MeetingRow m={m} open={open}/>)}</Block></section>}
function Processing({status}:Any){const steps=[['Recording saved',5],['Whisper transcription',55],['AI meeting analysis',92],['Results saved',100]];return <div className={'processing '+(status.state==='failed'?'failed':'')}><div className="processing-head"><div><b>{status.state==='failed'?'Processing stopped':status.state==='recorded'?'Queued for processing':'Processing meeting'}</b><span>{status.stage_detail}{status.queued?.length?` · ${status.queued.length} more waiting`:''}</span></div><strong>{status.progress}%</strong></div><div className="progress"><i style={{width:`${status.progress}%`}}/></div><div className="processing-steps">{steps.map(([label,value]:any)=><div className={status.progress>=value?'done':'pending'}><span>{status.progress>=value?'✓':'○'}</span><b>{label}</b><em>{value}%</em></div>)}</div>{status.error&&<p>{status.error}</p>}</div>}
function Block({title,children}:Any){return <div className="block"><h2>{title}</h2>{children?.length?children:<p className="empty">Nothing here yet.</p>}</div>}
function MeetingRow({m,open,remove}:Any){const [confirm,setConfirm]=useState(false),[err,setErr]=useState('');const busy=['recording','recorded','transcribing','analyzing'].includes(m.status);
 const row=<button className="meeting-row" onClick={()=>open(m.id)}><div><b>{m.title}</b><span>{fmt(m.started_at)} · {Math.round((m.duration_seconds||0)/60)} min</span></div><span className={'pill '+m.status}>{m.status}</span><ChevronRight size={17}/></button>;
 if(!remove)return row;
 const doRemove=async()=>{try{setErr('');await remove(m.id)}catch(e:any){setErr(e.message);setConfirm(false)}};
 return <div className="meeting-row-wrap">{row}{confirm?<div className="row-confirm"><span>Delete permanently?</span><button className="danger" onClick={doRemove}>Delete</button><button className="secondary" onClick={()=>setConfirm(false)}>Cancel</button></div>:<button className="row-delete" title={busy?'Available after processing finishes':'Delete meeting'} disabled={busy} aria-label={`Delete ${m.title}`} onClick={()=>setConfirm(true)}><Trash2 size={15}/></button>}{err&&<p className="download-error" role="alert">{err}</p>}</div>}
function MeetingList({meetings,open,remove}:Any){return <section><p className="eyebrow">LIBRARY</p><h1>Meetings</h1><p className="lede">Every conversation, locally stored.</p><div className="block">{meetings.map((m:Any)=><MeetingRow key={m.id} m={m} open={open} remove={remove}/>)}</div></section>}
function Task({t,toggle,showEvidence=false}:Any){const meta=[t.owner&&`Owner: ${t.owner}`,t.meeting_title,t.deadline_original&&`Due ${t.deadline_original}`].filter(Boolean).join(' · ');return <div className={'task '+t.status}><button className="check" onClick={()=>toggle(t)}>{t.status==='completed'?'✓':''}</button><div><b>{t.task}</b>{meta&&<span>{meta}</span>}{showEvidence&&t.evidence&&<small>Evidence: “{t.evidence}”</small>}</div><em className={t.priority}>{t.priority}</em></div>}
function ChangeRequest({change}:Any){const recipient=change.requested_of==='unknown_participant'?'Recipient not identified':change.requested_of==='team'?'Requested of the team':`Requested of ${change.requested_of}`;return <div className="change-request"><div><b>{change.change}</b><span>{recipient}{change.deadline_original&&` · Due ${change.deadline_original}`}</span>{change.evidence&&<small>Evidence: “{change.evidence}”</small>}</div><em className={change.priority}>{change.priority}</em></div>}
function Tasks({tasks,toggle}:Any){return <section><p className="eyebrow">ACTION</p><h1>My Tasks</h1><p className="lede">What you need to do next.</p><Block title="OPEN">{tasks.filter((x:Any)=>x.status==='open').map((t:Any)=><Task t={t} toggle={toggle}/>)}</Block><Block title="COMPLETED">{tasks.filter((x:Any)=>x.status==='completed').map((t:Any)=><Task t={t} toggle={toggle}/>)}</Block></section>}
function SearchPage({query,setQuery,open}:Any){const [items,setItems]=useState<Any[]>([]);useEffect(()=>{const t=setTimeout(()=>query&&api<Any[]>('/meetings?q='+encodeURIComponent(query)).then(setItems),200);return()=>clearTimeout(t)},[query]);return <section><p className="eyebrow">FIND</p><h1>Search</h1><input autoFocus className="searchbox" placeholder="Search meetings, people, decisions, tasks…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="block">{items.map(m=><MeetingRow m={m} open={open}/>)}</div></section>}
function Settings(){const [s,setS]=useState<Any>();useEffect(()=>{api<Any>('/settings').then(setS)},[]);if(!s)return <section><p>Loading…</p></section>;return <section><p className="eyebrow">PREFERENCES</p><h1>Settings</h1><Setting title="PROFILE" rows={[["Name",s.profile.name],["Aliases",s.profile.aliases.join(', ')]]}/><Setting title="AI" rows={[["Whisper model",s.ai.whisper_model],["Ollama model",s.ai.ollama_model],["Context window",`${s.ai.ollama_num_ctx.toLocaleString()} tokens`],["Ollama",s.ai.ollama.message||'Connected ✓']]}/><Setting title="AUDIO" rows={[["Input device",s.audio.blackhole?.name||'BlackHole 2ch'],["Status",s.audio.connected?'Connected ✓':s.audio.message]]}/><Setting title="STORAGE" rows={[["Meeting data",s.storage],["Privacy",s.privacy]]}/></section>}
function Setting({title,rows}:Any){return <div className="block settings-block"><h2>{title}</h2>{rows.map((r:any)=><div><span>{r[0]}</span><b>{r[1]}</b></div>)}</div>}
function Detail({m:initial,toggle,retry,remove,onSaved}:Any){
 const [m,setM]=useState(initial),[show,setShow]=useState(false),[segments,setSegments]=useState<Any[]>([]),[retrying,setRetrying]=useState(false),[retryError,setRetryError]=useState(''),[editing,setEditing]=useState(false),[saving,setSaving]=useState(false),[editError,setEditError]=useState(''),[downloading,setDownloading]=useState(false),[downloadError,setDownloadError]=useState(''),[confirmDelete,setConfirmDelete]=useState(false),[deleting,setDeleting]=useState(false),[deleteError,setDeleteError]=useState('');
 const [form,setForm]=useState<Any>({title:'',people_mentioned:[]});
 useEffect(()=>setM(initial),[initial]);
 useEffect(()=>{if(!['recorded','transcribing','analyzing'].includes(m.status))return;const timer=setInterval(()=>api<Any>('/meetings/'+m.id).then(setM),2500);return()=>clearInterval(timer)},[m.id,m.status]);
 const mentioned=m.people.filter((p:Any)=>p.type==='mentioned');
 const beginEdit=()=>{setForm({title:m.title,people_mentioned:mentioned.map((p:Any)=>({name:p.name,context:p.context||'',importance:p.importance||'medium'}))});setEditError('');setEditing(true)};
 const changePerson=(index:number,field:string,value:string)=>setForm((current:Any)=>({...current,people_mentioned:current.people_mentioned.map((person:Any,i:number)=>i===index?{...person,[field]:value}:person)}));
 const addPerson=()=>setForm((current:Any)=>({...current,people_mentioned:[...current.people_mentioned,{name:'',context:'',importance:'medium'}]}));
 const removePerson=(index:number)=>setForm((current:Any)=>({...current,people_mentioned:current.people_mentioned.filter((_:Any,i:number)=>i!==index)}));
 const saveInfo=async()=>{try{setSaving(true);setEditError('');const updated=await api<Any>('/meetings/'+m.id+'/info',{method:'PATCH',body:JSON.stringify(form)});setM(updated);setEditing(false);onSaved(updated)}catch(e:any){setEditError(e.message)}finally{setSaving(false)}};
 const isMine=(value:Any,field:string)=>value.is_mine===true||['hussain','husain'].includes((value[field]||'').toLowerCase());
 const mine=m.tasks.filter((t:Any)=>isMine(t,'owner')),other=m.tasks.filter((t:Any)=>!isMine(t,'owner'));
 const changes=m.requested_changes||[],myChanges=changes.filter((c:Any)=>isMine(c,'requested_of')),otherChanges=changes.filter((c:Any)=>!isMine(c,'requested_of'));
 const transcript=()=>{if(!show)api<Any[]>('/meetings/'+m.id+'/transcript').then(setSegments);setShow(!show)};
 const recover=async(retranscribe:boolean)=>{try{setRetrying(true);setRetryError('');await retry(m.id,retranscribe);setM(await api<Any>('/meetings/'+m.id))}catch(e:any){setRetryError(e.message)}finally{setRetrying(false)}};
 const downloadReport=async()=>{try{setDownloading(true);setDownloadError('');const file=await apiFile('/meetings/'+m.id+'/report.pdf');const url=URL.createObjectURL(file.blob);const link=document.createElement('a');link.href=url;link.download=file.filename||'meeting-report.pdf';document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch(e:any){setDownloadError(e.message)}finally{setDownloading(false)}};
 const doDelete=async()=>{try{setDeleting(true);setDeleteError('');await remove(m.id)}catch(e:any){setDeleteError(e.message);setDeleting(false);setConfirmDelete(false)}};
 const processing=['recorded','transcribing','analyzing'].includes(m.status),recoveryReady=!processing&&['failed','completed'].includes(m.status)&&m.can_retry;
 return <article><p className="eyebrow">MEETING RECORD</p><div className="meeting-heading"><div><h1>{m.title}</h1><p className="lede">{fmt(m.started_at)} – {m.ended_at?new Date(m.ended_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'Now'} · {Math.round(m.duration_seconds/60)} minutes</p></div>{!editing&&!processing&&m.status!=='recording'&&<div className="meeting-heading-actions">{m.status==='completed'&&<><button className="secondary" disabled={downloading} aria-busy={downloading} onClick={downloadReport}><Download size={14}/>{downloading?'Preparing PDF…':'Download PDF'}</button><button className="secondary" onClick={beginEdit}><Pencil size={14}/>Edit meeting info</button></>}<button className="secondary delete-trigger" disabled={deleting} onClick={()=>setConfirmDelete(true)}><Trash2 size={14}/>Delete</button></div>}</div>{downloadError&&<p className="download-error" role="alert">{downloadError}</p>}{deleteError&&<p className="download-error" role="alert">{deleteError}</p>}
 {confirmDelete&&<div className="delete-confirm" role="alertdialog"><div><b>Delete this meeting permanently?</b><p>The recording, transcript, AI report, tasks, and PDF source for “{m.title}” will be removed from this Mac. This cannot be undone.</p></div><div className="edit-actions"><button className="secondary" disabled={deleting} onClick={()=>setConfirmDelete(false)}>Keep meeting</button><button className="danger" disabled={deleting} onClick={doDelete}>{deleting?'Deleting…':'Delete permanently'}</button></div></div>}
 {editing&&<div className="meeting-edit"><div className="edit-intro"><div><b>Edit meeting info</b><p>Only the title and mentioned people will change. The AI report and transcript stay untouched.</p></div></div><label>Meeting title<input value={form.title} maxLength={200} onChange={e=>setForm({...form,title:e.target.value})}/></label><div className="readonly-grid"><label>Date<input readOnly value={new Date(m.started_at).toLocaleDateString()}/></label><label>Start time<input readOnly value={new Date(m.started_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})}/></label><label>End time<input readOnly value={m.ended_at?new Date(m.ended_at).toLocaleTimeString([],{hour:'numeric',minute:'2-digit'}):'—'}/></label><label>Duration<input readOnly value={`${Math.round(m.duration_seconds/60)} minutes`}/></label></div><div className="people-editor"><div className="people-editor-head"><div><b>People mentioned</b><span>Correct a name or add someone the AI missed.</span></div><button className="secondary" onClick={addPerson}><Plus size={14}/>Add person</button></div>{form.people_mentioned.length?form.people_mentioned.map((person:Any,index:number)=><div className="person-editor" key={index}><label>Name<input value={person.name} maxLength={120} placeholder="Person's name" onChange={e=>changePerson(index,'name',e.target.value)}/></label><label>Importance<select value={person.importance} onChange={e=>changePerson(index,'importance',e.target.value)}><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><label className="person-context">Context<textarea value={person.context} maxLength={500} placeholder="How this person was mentioned" onChange={e=>changePerson(index,'context',e.target.value)}/></label><button className="remove-person" aria-label={`Remove ${person.name||'person'}`} onClick={()=>removePerson(index)}><Trash2 size={16}/></button></div>):<p className="empty">No people added. Use “Add person” to include someone.</p>}</div>{editError&&<p className="edit-error">{editError}</p>}<div className="edit-actions"><button className="secondary" disabled={saving} onClick={()=>setEditing(false)}>Cancel</button><button className="primary" disabled={saving||!form.title.trim()||form.people_mentioned.some((p:Any)=>!p.name.trim())} onClick={saveInfo}>{saving?'Saving…':'Save meeting info'}</button></div></div>}
 {m.error&&<div className="error"><span>{m.error}</span></div>}{recoveryReady&&<div className="recovery"><div><b>{m.status==='failed'?'Recovery available':'Need a better report?'}</b><p>{m.transcript_available?'The saved transcript can go directly back to AI without running Whisper again.':'The original recording can be transcribed and analyzed again.'}</p></div><div className="recovery-actions">{m.transcript_available&&<button className="secondary" disabled={retrying} onClick={()=>recover(false)}>Analyze saved transcript again</button>}{m.recording_available&&<button className="secondary" disabled={retrying} onClick={()=>recover(true)}>Re-transcribe recording</button>}</div>{retryError&&<p className="retry-error">{retryError}</p>}</div>}<Section title="SUMMARY"><p className="summary">{m.summary||(processing?'Processing this meeting…':'No summary was generated because no speech was detected.')}</p></Section><Section title="HUSSAIN — WHAT YOU NEED TO DO"><div className="action-group"><h3>Confirmed tasks</h3>{mine.length?mine.map((t:Any)=><Task t={t} toggle={toggle} showEvidence/>):<Empty text="No confirmed tasks were assigned to Hussain."/>}</div><div className="action-group"><h3>Changes requested of you</h3>{myChanges.length?myChanges.map((c:Any)=><ChangeRequest change={c}/>):<Empty text="No additional changes were explicitly requested of Hussain."/>}</div></Section><List title="GOALS" items={m.goals}/><List title="KEY TOPICS" items={m.key_topics}/><List title="DECISIONS" items={m.decisions}/><Section title="OTHER PARTICIPANTS — ACTIONS"><div className="action-group"><h3>Confirmed tasks</h3>{other.length?other.map((t:Any)=><Task t={t} toggle={toggle} showEvidence/>):<Empty text="No tasks were confidently assigned to other participants."/>}</div><div className="action-group"><h3>Requested changes</h3>{otherChanges.length?otherChanges.map((c:Any)=><ChangeRequest change={c}/>):<Empty text="No other requested changes were found."/>}</div></Section><Section title="PEOPLE MENTIONED">{mentioned.length?mentioned.map((p:Any)=><div className="person"><b>{p.name}</b><p>{p.context}</p></div>):<Empty text="No people were mentioned."/>}</Section><List title="NEXT STEPS" items={m.next_steps} ordered/><Section title="FULL TRANSCRIPT"><button className="disclosure" onClick={transcript}>{show?<ChevronDown/>:<ChevronRight/>} {show?'Hide':'Show'} transcript</button>{show&&<div className="transcript">{segments.length?segments.map(s=><div><time>{new Date(s.start*1000).toISOString().slice(14,19)}</time><b>{s.speaker||'Speaker'}</b><p>{s.text}</p></div>):<p className="empty">No speech was detected. The saved recording contains silence.</p>}</div>}</Section></article>
}
function Section({title,children}:Any){return <div className="section"><h2>{title}</h2>{children}</div>} function Empty({text}:Any){return <p className="empty">{text}</p>} function List({title,items,ordered}:Any){const vals=items.map((x:Any)=>x.value||x);return <Section title={title}>{vals.length?(ordered?<ol>{vals.map((x:string)=><li>{x}</li>)}</ol>:<ul>{vals.map((x:string)=><li>{x}</li>)}</ul>):<Empty text="No information available."/>}</Section>}
export default App;
